name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirement.txt

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code for deployment
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Deploy to EC2 via SSH
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to your app directory on the EC2 instance
            cd /home/ubuntu/legal_ai_backend

            # Pull the latest code from the GitHub repository
            git pull origin main

            # (Re)install dependencies in case they have changed
            python3 -m pip install --upgrade pip
            pip3 install -r backend/requirement.txt

            # Stop the currently running FastAPI server (if any)
            pkill -f main.py || true

            # Start the FastAPI app using python3 main.py in the background
            nohup python3 backend/main.py > server.log 2>&1 &
